Synchronous reactive application shell in C
===========================================
A2FF
v0.1
:toc:
:numbered:
:data-uri:
:icons:
:language: c
//:language: javascript
//:src_numbered: numbered
:source-highlighter: highlightjs



Time-chasing loop
-----------------
Using an OS timer or periodic thread is not great for advanced functionality such as elastic period and catching up late iterations as opposed to simply bailing out - unless of course the OS provides such services.

A busy-waiting synchronous loop can be implemented with just a time reference.
If preemptive multitasking is needed, busy-waiting can be replaced with a system `sleep()` that will yield to other threads.

.Library
[source,c]
----------------------------------------
typedef unsigned long long U64;
typedef unsigned int U32;
typedef unsigned short U16;
typedef unsigned char U8;
typedef U64 Time;

extern Time getTime();      // absolute, i.e. relative to any past epoch
extern void fatal();

#if OS_HAS_ABSOLUTE_SLEEP
extern void waitUntil(Time when);
#elif OS_HAS_RELATIVE_SLEEP
extern void waitDelay(Time delay);
inline void waitUntil(Time when) { waitDelay(when-getTime()); }
#else
inline void waitUntil(Time when) { do {} while(getTime()<when); }
#endif
----------------------------------------

.Time chasing with a time counter
[source,c]
----------------------------------------
void loopAdd(Time period) {
  Time now = getTime();
  for(;;) {
    // ... nominal ...

    now += period; waitUntil(now); }}
----------------------------------------

.Time chasing with a cycle counter
[source,c]
----------------------------------------
void loopMul(Time period) {
  unsigned cycle = 0; Time epoch = getTime();
  for(;;) {
    // ... nominal ...

    ++ cycle; waitUntil(epoch+cycle*period); }}
----------------------------------------

.Combining the cycle and time counters for convenience in the loop body
[source,c]
----------------------------------------
void loopAdd(Time period) {
  unsigned cycle = 0; Time now = getTime();
  for(;;) {
    // ... nominal ...

    ++ cycle; now += period; waitUntil(now); }}

void loopMul(Time period) {
  unsigned cycle = 0; Time epoch = getTime(), now = epoch;
  for(;;) {
    // ... nominal ...

    ++ cycle; now = epoch+cycle*period; waitUntil(now); }}
----------------------------------------

.Faulting on a timing overrun
[source,c]
----------------------------------------
void loopAdd(Time period) {
  Time now = getTime();
  for(;;) {
    // ... nominal ...

    now += period;
    Time current = getTime();
    if(current>=now) {              // late!
      // ... fault ...

      fatal(); }
    waitUntil(now); }}
----------------------------------------

.Recovering from a timing overrun by skipping multiple frames
[source,c]
----------------------------------------
void loopAdd(Time period) {
  Time now = getTime();
  for(;;) {
    // ... nominal ...

    now += period;
    Time current = getTime();
    if(current>=now) {              // late!
      // ... recovery ...

      current = getTime();
      unsigned missed = (current-now)/period;
      now += missed*period;
    }
    waitUntil(now); }}
----------------------------------------

.Recovering iteratively
[source,c]
----------------------------------------
void loopAdd(Time period) {
  Time now = getTime();
  bool overrun = false;
  for(;;) {
    if(overrun)
      // ... late ...
    else
      // ... nominal ...

    now += period; Time current = getTime();
    if(current>=now) overrun = true;
    else { overrun = false; waitUntil(now); }}}
----------------------------------------


Self-checking computer
----------------------
The computer self-checks its ALU by running a program with predictable non-trivial cyclic output.
Bitwise operators are checked with a xorshift maximum-period 16-bit LFSR.
Arithmetic operators are checked with addition and division of coprimes.
Memory and bus addressing are checked with an in-memory permutation.

.ALU self-check
[source,c]
----------------------------------------
#define CHECK_PERIOD 120
#define CHECK_COUNT (sizeof(selfChecks)/sizeof(*selfChecks))
#define CHECK_ALL ((1<<CHECK_COUNT)-1)
typedef struct SelfCheck {
	U16 (*check)(U16 state);
  U16 seed;
  U16 expected[CHECK_PERIOD];
} SelfCheck;

U16 checkCounter(U16 x) { return x+1; }

// parity-enhanced Gray numbers have a trivial incr in binary (no loops)
// n-bits PE-Gray numbers require uints with n+1 bits
// parity is in the LSB, the associated Gray number is pe_gray>>1
// PE-Gray numbers all have odd parity; caller needs to prevent overflow
// else pegray_inc() will fail (return not a PE-Gray number), thus:
// precondition: x<2**n and parity(x)==odd
// postcondition: parity(x)==odd and x=<2**n
U16 pegray_inc(U16 x) {
  U16 msb = x&~(x-1); return x^((msb<<1)|1); }

#define PEGRAY_BITS 15
U16 pegray_modinc(U8 b, U16 x) {
  return x==1<<p ? 1 : pegray_inc(x); }

U16 checkGray(U16 x) {
  return pegray_modinc(15, x); } // period==2**15==32768

U16 checkLfsr(U16 x) { // Metcalf xorshift, period==65535
  x ^= x>>7; x ^= x<<9; x ^= x>>13; return x; }

// any coprime of the modulus will do as an addend
// 0xA5A5 0x5A5A 0x5AA5 etc. are not coprimes (typ. by +-1)
// => chose aperiodic binary alternance 0b101100111000==2872
volatile const U16 coprime = 2872, modulus = 65535,
                   nonTrivMult = 12345, nonTrivId = 65536-12345;
U16 checkAlu(U16 x) {
  return (x*nonTrivMult+x*nonTrivId+coprime)%modulus; }

volatile const U16 perm64k[65536] = { 0xDEAD, /* fill with Metcalf 7,9,8 */ };
U16 checkRam(U16 x) {
  return perm64k[x]; }

SelfCheck const selfChecks[] = {
	{ checkGray, 1, [ ... ] },  // CAUTION: only odd-parity numbers
	{ checkCounter, 1234, [1234+1, 1234+2, ...] },
	{ checkLfsr, 2345, [ ... ] },
	{ checkAlu, 3456, [ ... ] },
	{ checkRam, 5678, [ ... ] }}

unsigned checkPhase;
U16 checkStates[CHECK_COUNT];
void checkInit() {
  checkPhase = 0;
  for(int i = 0; i<CHECK_COUNT; ++ i) checkStates[i] = selfChecks[i].seed; }

void checkStep() {
  unsigned consensus = 0;
  for(int i = 0; i<CHECK_COUNT; ++ i) {
    checkStates[i] = selfChecks[i].check(checkStates[i]);
    consensus = (consensus<<1)
              | (checkStates[i]==selfChecks[i].expected[checkPhase]); }
  ++ checkPhase; if(checkPhase>=CHECK_PERIOD) checkPhase = 0;
  if(consensus!=CHECK_ALL) fatal(); }}
// insert some pragma such that fatal() is the fall-through path
// and the branch skipping over fatal() is predicted not-taken
// and prevent prediction by accessing some guarded memory from fatal()

#include "xxhash.h"
extern const char __text__[], const char __end__[];
extern XXH128_hash_t text_xxHash128;;
void chksumProg() {
  XXH128_hash_t h = XXH3(__text__, __end__-__text__, 0);
  if(!XXH128_isEqual(&h, &text_xxHash128)) fatal(); }

extern void spawn(void (*entry)()); // spawn at foreground priority

extern void appInit(); extern void appStep();

void periodicTask() {
  for(;;) {
    appStep(); checkStep();
    /* yield until next period (see previous ยง) */ }}

void main() {
  checkInit(); appInit(); spawn(periodicTask);
  for(;;) { // background priority-preemptive
    chksumProg(); }}
----------------------------------------

References:

- [https://en.wikipedia.org/wiki/Linear-feedback_shift_register] 
- [https://en.wikipedia.org/wiki/Xorshift]
- [https://en.wikipedia.org/wiki/Linear_congruential_generator]
- [http://www.retroprogramming.com/2017/07/xorshift-pseudorandom-numbers-in-z80.html]
- [https://stackoverflow.com/questions/17490431/gray-code-increment-function/17493235#17493235]

According to Metcalf, 60 triples have maximum period, of which 4 pass basic randomness tests: 6, 7, 13; 7, 9, 8; 7, 9, 13; 9, 7, 13.


// vim: set syntax=asciidoctor textwidth=0 shiftwidth=2 softtabstop=2 expandtab :
